# Generated by Django 5.0 on 2024-01-07 01:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_parts17g_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsSK850',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(editable=False, max_length=100)),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
