# Generated by Django 5.0 on 2024-01-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_glbfile333g_alter_parts333g_glb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glbfile333g',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/model333G/'),
        ),
    ]
